baseURL: /
languageCode: en-us
summaryLength: '10'
theme: kross-hugo-data-science
title: IBS
params:
  address: Johannesburg, South Africa
  author: Eddie Cheteni
  baidu_analytics_id: ''
  baidu_site_verification: ''
  contact:
    enable: yes
    form_action: '#'
  cookies:
    enable: no
    expire_days: 2
  copyright: Copyright &copy; 2024 Insight Base Solutions
  description: An example data science portfolio with kross theme.
  email: info@insigtbase.co.za
  google_analytics_id: ''
  home: Home
  logo: ''
  map:
    enable: no
    gmap_api: https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png
  phone: +27 69 741 1319
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/google-map/map.js
  preloader:
    enable: yes
    preloader: images/preloader.gif
  social:
    - URL: '#'
      icon: ti-linkedin
    - URL: '#'
      icon: ti-github
    - URL: '#'
      icon: ti-youtube
    - URL: '#'
      icon: ti-twitter-alt
  theme_color: '#003049'
menu:
  main:
    - URL: portfolio
      name: Portfolio
      weight: 3
    - URL: services
      name: Services
      weight: 3
    - URL: contact
      name: Contact
      weight: 4
